spring.application.name=team3ProjectAPIGateway
server.port=9000

# ===== JWT =====
jwt.secret=${JWT_SECRET:team3-project-jwt-secret-key-must-be-at-least-32-bytes-long}

# ===== Eureka =====
eureka.client.service-url.defaultZone=http://100.71.98.3:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=100.71.98.3
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===== Gateway Routes =====
# 이게 곧 우리가 만든 서비스들을 연결해주는 역할을 함.
# User/Auth Service
# spring.cloud.gateway.routes[0].id=auth-service
# spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
# spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

# Sourcing Service
spring.cloud.gateway.routes[2].id=sourcing-service
spring.cloud.gateway.routes[2].uri=lb://SOURCING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/sourcing/**

# Payment Service
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/payment/**

# Shop Service
spring.cloud.gateway.routes[4].id=shop-service
spring.cloud.gateway.routes[4].uri=lb://SHOP-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/shop/**
