spring.application.name=team3Project
server.port=8082

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MariaDB ??
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/team3project
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Thymeleaf
spring.thymeleaf.cache=false

# Devtools - ???? ?? ??
spring.devtools.livereload.enabled=true

# Mail (Gmail SMTP) - vbkh63k@gmail.com ?? ??
# ??: Gmail ?? ????? ?? ? ????? ???? ?
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vbkh63k@gmail.com
spring.mail.password=cugqieqlaajqrkzv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000

# Eureka Client ??
eureka.client.service-url.defaultZone=http://100.71.98.3:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=100.70.104.88
eureka.instance.non-secure-port=8082
spring.cloud.inetutils.preferred-networks=100.
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}