spring.application.name=team3Project

# 1. 공통 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 2. 'local' 프로필을 기본으로 활성화 (중요!)
spring.profiles.include=local

# 3. Dialect 명시 (DB 연결 실패 시에도 명확한 에러 확인 가능)
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
