spring.application.name=Order-Processing-Service

# 파일 상단 작성
# 민정기: 8080 진:8081 김지연:8082 이용호:8083 현재진:8084
server.port=8083

spring.datasource.url=jdbc:mariadb://100.119.201.17:3306/team3project?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=0000

eureka.client.service-url.defaultZone=http://100.119.201.17:8761/eureka/

#spring.cloud.gateway.routes[2].id=Order-Processing-Service
#spring.cloud.gateway.routes[2].uri=lb://ORDER-PROCESSING-SERVICE
#spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**,/cards/**,/settlements/**,/shipping/**

eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
# eureka.instance.ip-address= 사진의 this device:옆에 ip 주소 입력 - 일단 다른 거 다하고 정기님 초대 받은 이후 진행
eureka.instance.ip-address=100.82.219.117
# 민정기: 8080 진:8081 김지연:8082 이용호:8083 현재진:8084
eureka.instance.non-secure-port=8083
spring.cloud.inetutils.preferred-networks=100.

minio.url=http://100.71.98.3:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=sourcing-images

spring.thymeleaf.cache=false
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}

spring.jpa.hibernate.ddl-auto=update

